{% set version = '1.0.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sparklyr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/sparklyr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sparklyr/sparklyr_{{ version }}.tar.gz
  sha256: 9dd0fed24a5f381f1d7413df92b9fef5b1cbdcbf0c677bcabe083ba33637fbe7

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-dbi >=0.6_1
    - r-assertthat
    - r-base64enc
    - r-config >=0.2
    - r-dbplyr >=1.1.0
    - r-digest
    - r-dplyr >=0.7.2
    - r-ellipsis >=0.1.0
    - r-forge
    - r-generics
    - r-httr >=1.2.1
    - r-jsonlite >=1.4
    - r-openssl >=0.8
    - r-purrr
    - r-r2d3
    - r-rappdirs
    - r-rlang >=0.1.4
    - r-rprojroot
    - r-rstudioapi >=0.6
    - r-tibble
    - r-tidyr
    - r-withr
    - r-xml2
  run:
    - r-base
    - r-dbi >=0.6_1
    - r-assertthat
    - r-base64enc
    - r-config >=0.2
    - r-dbplyr >=1.1.0
    - r-digest
    - r-dplyr >=0.7.2
    - r-ellipsis >=0.1.0
    - r-forge
    - r-generics
    - r-httr >=1.2.1
    - r-jsonlite >=1.4
    - r-openssl >=0.8
    - r-purrr
    - r-r2d3
    - r-rappdirs
    - r-rlang >=0.1.4
    - r-rprojroot
    - r-rstudioapi >=0.6
    - r-tibble
    - r-tidyr
    - r-withr
    - r-xml2

test:
  commands:
    - $R -e "library('sparklyr')"           # [not win]
    - "\"%R%\" -e \"library('sparklyr')\""  # [win]

about:
  home: http://spark.rstudio.com
  license: Apache 2.0
  summary: R interface to Apache Spark, a fast and general engine for big data processing, see
    <http://spark.apache.org>. This package supports connecting to local and remote
    Apache Spark clusters, provides a 'dplyr' compatible back-end, and provides an interface
    to Spark's built-in machine learning algorithms.
  license_family: APACHE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: sparklyr
# Type: Package
# Title: R Interface to Apache Spark
# Version: 1.0.0
# Authors@R: c( person("Javier", "Luraschi", email = "javier@rstudio.com", role = c("aut", "cre")), person("Kevin", "Kuo", role = "aut", email = "kevin.kuo@rstudio.com", comment = c(ORCID = "0000-0001-7803-7901")), person("Kevin", "Ushey", role = "aut", email = "kevin@rstudio.com"), person("JJ", "Allaire", role = "aut", email = "jj@rstudio.com"), person("Samuel", "Macedo", role = "ctb", email = "samuelmacedo@recife.ifpe.edu.br"), person(family = "RStudio", role = c("cph")), person(family = "The Apache Software Foundation", role = c("aut", "cph")) )
# Maintainer: Javier Luraschi <javier@rstudio.com>
# Description: R interface to Apache Spark, a fast and general engine for big data processing, see <http://spark.apache.org>. This package supports connecting to local and remote Apache Spark clusters, provides a 'dplyr' compatible back-end, and provides an interface to Spark's built-in machine learning algorithms.
# License: Apache License 2.0 | file LICENSE
# SystemRequirements: Spark: 1.6.x or 2.x
# URL: http://spark.rstudio.com
# BugReports: https://github.com/rstudio/sparklyr/issues
# LazyData: TRUE
# RoxygenNote: 6.1.0
# Depends: R (>= 3.2)
# Imports: assertthat, base64enc, config (>= 0.2), DBI (>= 0.6-1), dplyr (>= 0.7.2), dbplyr (>= 1.1.0), digest, forge, generics, httr (>= 1.2.1), jsonlite (>= 1.4), methods, openssl (>= 0.8), purrr, r2d3, rappdirs, rlang (>= 0.1.4), rprojroot, rstudioapi (>= 0.6), tibble, tidyr, withr, xml2, ellipsis (>= 0.1.0)
# Suggests: broom, ggplot2, glmnet, janeaustenr, Lahman, mlbench, nnet, nycflights13, R6, RCurl, reshape2, shiny (>= 1.0.1), testthat
# NeedsCompilation: no
# Packaged: 2019-02-25 08:02:41 UTC; javierluraschi
# Author: Javier Luraschi [aut, cre], Kevin Kuo [aut] (<https://orcid.org/0000-0001-7803-7901>), Kevin Ushey [aut], JJ Allaire [aut], Samuel Macedo [ctb], RStudio [cph], The Apache Software Foundation [aut, cph]
# Repository: CRAN
# Date/Publication: 2019-02-25 08:30:03 UTC
