appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: OH4bifUNCWAQFEtFXh5n8FMHaynW+y/gHR097XB3iePGfakGPEHpnhlPcOl0NsSZAfUrU8FiACH6E0apkCwy4196j3V0/+Cg4lHd33YDsfyuAX79BfXccDILGlryi76F9k8uGspb1cuYUiZ+nvreoOGwWRzHAEcaenPUHew87macsnmbvnZ9N3f4OhUFj0GId/JkRZPtkU/2bz5gGbGn1RIcWuJVEnMOvZbphmoCwpA8ukvv4twbSgbjh9ZOpqOnggSLaSzTp4Xtt2sTS3bzYYaufzZ+NrjNB5Bo1ATnDoOcQ7ViLOXD4VHS1MDOGkIDABFiHoHVexFNkIx5jsmElgkDWmbtIdItuWVDZLudMclp4old6oJnuRUoROn+CJ09RFrLvVqWnic/6OM/NLi4919lxSnwuJR7dz5Aiko30mEo3nlJHaxlLw2/nPgteQWpUR4swk4VWSttC/uQh1pA548zgVtkIxWynhG6qiExKbzrvBBbnJJIU5U0GVe17f3CiIny5T6/y5Ni3yIvGS6WemetLZ8PnBG/REQvEpGfVEROPY0+VZoOh/626Vva+xMgZdoPeXqFiaEAud1xFj8LBDZE/QpXQjTQ7QC33zak4w+K8FDJhTE5Rr7vYAW8bJpQQl760C8ayjc50jzw6Z859xf4D7hL91RkB+g5fK+41jQ=
conda_forge_output_validation: true
